### ISSUE TITLE
Wand bench crash [r15]

### ISSUE THREAD

**Issue by KryptonCaptain** [Advanced-Thaumaturgy2/Advanced-Thaumaturgy2#4]
Put a wand in the wand bench, then a rod in the rod slot. Then it crashed

```
---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 22/11/16 2:19 PM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at net.ixios.advancedthaumaturgy.tileentities.TileWandbench.swapRod(TileWandbench.java:69)
	at net.ixios.advancedthaumaturgy.tileentities.TileWandbench.buildWand(TileWandbench.java:175)
	at net.ixios.advancedthaumaturgy.tileentities.TileWandbench.func_70296_d(TileWandbench.java:203)
	at net.minecraft.inventory.Slot.func_75218_e(Slot.java:83)
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:78)
	at net.minecraft.inventory.Container.func_75144_a(SourceFile:157)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:419)
	at codechicken.nei.guihook.GuiContainerManager.handleSlotClick(GuiContainerManager.java:504)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.public_func_146984_a(GuiContainer.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.callHandleMouseClick(DefaultSlotClickHandler.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.handleSlotClick(DefaultSlotClickHandler.java:17)
	at codechicken.nei.guihook.GuiContainerManager.handleMouseClick(GuiContainerManager.java:453)
	at net.minecraft.client.gui.inventory.GuiContainer.managerHandleMouseClick(GuiContainer.java)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:590)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.ixios.advancedthaumaturgy.tileentities.TileWandbench.swapRod(TileWandbench.java:69)
	at net.ixios.advancedthaumaturgy.tileentities.TileWandbench.buildWand(TileWandbench.java:175)
	at net.ixios.advancedthaumaturgy.tileentities.TileWandbench.func_70296_d(TileWandbench.java:203)
	at net.minecraft.inventory.Slot.func_75218_e(Slot.java:83)
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:78)
	at net.minecraft.inventory.Container.func_75144_a(SourceFile:157)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:419)
	at codechicken.nei.guihook.GuiContainerManager.handleSlotClick(GuiContainerManager.java:504)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.public_func_146984_a(GuiContainer.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.callHandleMouseClick(DefaultSlotClickHandler.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.handleSlotClick(DefaultSlotClickHandler.java:17)
	at codechicken.nei.guihook.GuiContainerManager.handleMouseClick(GuiContainerManager.java:453)
	at net.minecraft.client.gui.inventory.GuiContainer.managerHandleMouseClick(GuiContainer.java)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:590)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)

-- Affected screen --
Details:
	Screen name: net.ixios.advancedthaumaturgy.gui.GuiWandbench

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['KryptonCaptain'/108, l='MpServer', x=1433.38, y=57.62, z=-1217.48]]
	Chunk stats: MultiplayerChunkCache: 441, 450
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (1430,4,-1219), Chunk: (at 6,0,13 in 89,-77; contains blocks 1424,0,-1232 to 1439,255,-1217), Region: (2,-3; contains chunks 64,-96 to 95,-65, blocks 1024,0,-1536 to 1535,255,-1025)
	Level time: 158741 game time, 84000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 8 total; [EntityWolfArmored['Wolf'/102, l='MpServer', x=1437.16, y=56.00, z=-1219.03], EntityWolfArmored['Wolf'/103, l='MpServer', x=1437.50, y=56.00, z=-1216.50], EntityWolfArmored['Wolf'/104, l='MpServer', x=1436.25, y=56.00, z=-1220.28], EntityWolfArmored['Wolf'/105, l='MpServer', x=1437.44, y=56.00, z=-1215.56], EntityWolfArmored['Wolf'/106, l='MpServer', x=1440.50, y=56.00, z=-1218.50], EntityWolfArmored['Wolf'/107, l='MpServer', x=1440.63, y=56.00, z=-1220.47], EntityTrail['unknown'/251, l='MpServer', x=1433.38, y=57.62, z=-1217.48], EntityClientPlayerMP['KryptonCaptain'/108, l='MpServer', x=1433.38, y=57.62, z=-1217.48]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1429867776 bytes (1363 MB) / 2361393152 bytes (2252 MB) up to 2863661056 bytes (2731 MB)
	JVM Flags: 5 total; -XX:+AggressiveOpts -XX:+UseFastAccessorMethods -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2048m -Xmx3072m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_D1 56 mods loaded, 56 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCHIJAAAA	BugfixMod{2.5.0} [BugfixMod] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAAAA	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) 
	UCHIJAAAA	WitchingGadgetsCore{1.2.0} [Witching Gadgets Core] (minecraft.jar) 
	UCHIJAAAA	HxCCore-ASM{1.12.4} [HxCKDMS Core ASM] (minecraft.jar) 
	UCHIJAAAA	FastCraft{1.23} [FastCraft] (fastcraft-1.23.jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	ForgeMultipart{1.1.2.331} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	UCHIJAAAA	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-538.jar) 
	UCHIJAAAA	ForbiddenMagic{1.7.10-0.575} [Forbidden Magic] (Forbidden Magic-1.7.10-0.575.jar) 
	UCHIJAAAA	DummyCore{1.13} [DummyCore] (DummyCore1.13.jar) 
	UCHIJAAAA	thaumicbases{1.4.1710.2} [Thaumic Bases] (ThaumicBased 1.4.1-1710-2.jar) 
	UCHIJAAAA	ThaumicExploration{0.6.0} [Thaumic Exploration] (ThaumicExploration-1.7.10-1.1-55.jar) 
	UCHIJAAAA	ThaumicHorizons{1.1.9.7} [Thaumic Horizons] (thaumichorizons_hoboedit-1.1.9.7.jar) 
	UCHIJAAAA	AdvancedThaumaturgy{2.0} [Advanced Thaumaturgy] (AdvancedThaumaturgy-2.0-1.7.10-15.jar) 
	UCHIJAAAA	algaecraft{1.5.8} [AlgaeCraft] (algaecraft-[1.7.10]1.5.10.jar) 
	UCHIJAAAA	antiidconflict{1.3.5} [Anti Id Conflict] (AntiIdConflict-1.3.5-1.7.10.jar) 
	UCHIJAAAA	Automagy{0.28.2} [Automagy] (Automagy-1.7.10-0.28.2.jar) 
	UCHIJAAAA	CleanView{1.7.10-v2} [CleanView] (CleanView-1.7.10-v2.jar) 
	UCHIJAAAA	cosmeticarmorreworked{1.7.10-v5d} [CosmeticArmorReworked] (CosmeticArmorReworked-1.7.10-v5d.jar) 
	UCHIJAAAA	endercore{1.7.10-0.2.0.39_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.39_beta.jar) 
	UCHIJAAAA	gadomancy{1.0.7.3} [Gadomancy] (gadomancy-1.7.10-1.0.7.3.jar) 
	UCHIJAAAA	HelpFixer{1.0.7} [HelpFixer] (HelpFixer-1.0.7.jar) 
	UCHIJAAAA	HxCCore{1.12.4} [HxC-Core] (HxCCore-1.7.10-1.12.4-universal.jar) 
	UCHIJAAAA	iChunUtil{4.2.2} [iChunUtil] (iChunUtil-4.2.2.jar) 
	UCHIJAAAA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCHIJAAAA	magianaturalis{0.1.5b} [Magia Naturalis] (MagiaNaturalis-1.7.10-0.1.5b.jar) 
	UCHIJAAAA	mdeco{0.3.5} [Magical Decorations] (MagicalDecorations-0.3.5.jar) 
	UCHIJAAAA	MineTweaker3{3.0.10} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.10B.jar) 
	UCHIJAAAA	modtweaker2{0.9.5} [Mod Tweaker 2] (ModTweaker2-0.9.5.jar) 
	UCHIJAAAA	neiintegration{1.1.2} [NEI Integration] (NEIIntegration-MC1.7.10-1.1.2.jar) 
	UCHIJAAAA	NodalMechanics{1.7.10R1.0} [NodalMechanics] (NodalMechanics-1.7-1.0-7.jar) 
	UCHIJAAAA	Railcraft{9.12.1.0} [Railcraft] (Railcraft_1.7.10-9.12.1.0.jar) 
	UCHIJAAAA	symcalc{0.14} [Symcalc] (symcalc-0.14.jar) 
	UCHIJAAAA	Tabula{4.1.1} [Tabula] (Tabula-4.1.1.jar) 
	UCHIJAAAA	TaintedMagic{r7.4} [Tainted Magic] (Tainted-Magic-r7.4.jar) 
	UCHIJAAAA	tcinventoryscan{1.0.11} [TC Inventory Scanning] (tcinventoryscan-mc1.7.10-1.0.11.jar) 
	UCHIJAAAA	Unthaumic{1.7.10-1.1} [Thaumcraft Minus Thaumcraft] (Thaumcraft Minus Thaumcraft-1.7.10-1.1.jar) 
	UCHIJAAAA	thaumcraftneiplugin{@VERSION@} [Thaumcraft NEI Plugin] (thaumcraftneiplugin-1.7.10-1.7a.jar) 
	UCHIJAAAA	ThaumicMachina{0.2.1} [Thaumic Machina] (Thaumic Machina-1.7.10-0.2.1.jar) 
	UCHIJAAAA	thaumicdyes{1.3} [Thaumic Dyes] (Thaumic-Dyes-[1.7.10] 1.4.0-1.jar) 
	UCHIJAAAA	thaumicsanity{1.0} [thaumicsanity] (thaumicSanity-1.0-1.7.10-9.jar) 
	UCHIJAAAA	TravellersGear{1.16.4} [Traveller's Gear] (TravellersGear-1.7.10-1.16.4.jar) 
	UCHIJAAAA	WarpTheory{1.7.10R1.0f.Custom} [WarpTheory] (WarpTheory-1.7.10-1.0f-DEV.jar) 
	UCHIJAAAA	wawla{1.3.3} [What Are We Looking At] (Wawla-1.3.3-1.7.10.jar) 
	UCHIJAAAA	WitchingGadgets{1.2.0} [Witching Gadgets] (WitchingGadgets-1.7.10-1.2.0.jar) 
	UCHIJAAAA	wolfarmor{1.0.2} [Wolf Armor and Storage] (wolfarmor-1.0.3.jar) 
	UCHIJAAAA	McMultipart{1.1.2.331} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	UCHIJAAAA	aobd{2.9.1} [Another One Bites The Dust] (AOBD-2.9.1.jar) 
	UCHIJAAAA	ForgeMicroblock{1.1.2.331} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4358' Renderer: 'Intel(R) HD Graphics 4000'
	HxCKDMS Crash Check: Will analyze crash log and send the error to github if HxCKDMS Core is possibly involved.
	Launched Version: MultiMC5
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 4000 GL version 4.0.0 - Build 10.18.10.4358, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [kryptTexTweaks.zip, netherores.zip, strata.zip, lang fix.zip, Krypt's CartLivery Pack.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: On (4)
	OptiFine Version: OptiFine_1.7.10_HD_D1
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 4
	Antialiasing: 0
	Multitexture: false
	OpenGlVersion: 4.0.0 - Build 10.18.10.4358
	OpenGlRenderer: Intel(R) HD Graphics 4000
	OpenGlVendor: Intel
	CpuCount: 8
```

**Comment by spannerman79** [comment]
I *think* this *might* be a conflict with [Thaumic Machina](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2200956-wip-1-7-10-open-beta-thaumcraft-4-2-addon-thaumic) - Thaumic Machina does Wand Augmentation.

**Comment by KryptonCaptain** [comment]
It's not T.Machina - just tested.

Crash occurs when I place a Mercurial Wand in the wand slot, and a Mercurial Rod in the rod slot.
Bench seems to work fine with other tested wands/rods so far

**Comment by ToFam** [comment]
Should be fixed with build 16
